namespace TestAudit.Helpers.Audit;

public enum AuditCommand
{
    Login,
    Logout,
    Registration,
    ResetPassword,
    UpdateUserprofile,
    DisableUser,
    SetUserRole,
    DelegateUserRole,
    RevokeUserRole,
    CreateGroup,
    IncludeUserInGroup,
    DeleteUserFromGroup,
    SetUserRoleInGroup,
    DelegateUserRoleInGroup,
    RevokeUserRoleInGroup,
    UpdateGroup,
    DeleteGroup,
    CreateWorkspace,
    IncludeGroupInWorkspace,
    DeleteGroupFromWorkspace,	
    UpdateWorkspace,
    DisableWorkspace,
    CreateGeoLayerInWorkspace,
    UpdateGeoLayer,
    DeleteGeoLayer,
    CreateGeoObject,
    UpdateGeoObject,
    DeleteGeoObject,
    CreateDataCatalog,
    UpdateDataCatalog,
    DeleteDataCatalog,
    CreateStatisticalGeoObjectsReport,
    CreateAuditReport
}